// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zyziiuinoldnrnjaehev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5emlpdWlub2xkbnJuamFlaGV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzNjM0NTQsImV4cCI6MjA1MDkzOTQ1NH0.X7Zb2ToRoPSFiZJTlrxMFpW9Q077BW_yF0-7ajtj4Nk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);